/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcairo_TextExtents_Naam */

#ifndef _Included_org_jcairo_TextExtents_Naam
#define _Included_org_jcairo_TextExtents_Naam
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
