/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcairo_CairoContext */

#ifndef _Included_org_jcairo_CairoContext
#define _Included_org_jcairo_CairoContext
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jcairo_CairoContext_ANTIALIAS_DEFAULT
#define org_jcairo_CairoContext_ANTIALIAS_DEFAULT 0L
#undef org_jcairo_CairoContext_ANTIALIAS_NONE
#define org_jcairo_CairoContext_ANTIALIAS_NONE 1L
#undef org_jcairo_CairoContext_ANTIALIAS_GRAY
#define org_jcairo_CairoContext_ANTIALIAS_GRAY 2L
#undef org_jcairo_CairoContext_ANTIALIAS_SUBPIXEL
#define org_jcairo_CairoContext_ANTIALIAS_SUBPIXEL 3L
#undef org_jcairo_CairoContext_FILL_RULE_WINDING
#define org_jcairo_CairoContext_FILL_RULE_WINDING 0L
#undef org_jcairo_CairoContext_FILL_RULE_EVEN_ODD
#define org_jcairo_CairoContext_FILL_RULE_EVEN_ODD 1L
/*
 * Class:     org_jcairo_CairoContext
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_init
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    status
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoContext_status
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    save
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_save
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    restore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_restore
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    pushGroup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_pushGroup
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    popGroup
 * Signature: ()Lorg/jcairo/CairoPattern;
 */
JNIEXPORT jobject JNICALL Java_org_jcairo_CairoContext_popGroup
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    popGroupToSource
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_popGroupToSource
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setSourceRGB
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setSourceRGB
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setSourceRGBA
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setSourceRGBA
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setSource
 * Signature: (Lorg/jcairo/CairoPattern;)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setSource
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setSourceSurface
 * Signature: (Lorg/jcairo/CairoSurface;DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setSourceSurface
  (JNIEnv *, jobject, jobject, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    getSource
 * Signature: ()Lorg/jcairo/CairoPattern;
 */
JNIEXPORT jobject JNICALL Java_org_jcairo_CairoContext_getSource
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setAntialias
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setAntialias
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    getAntialias
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoContext_getAntialias
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setDash
 * Signature: ([DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setDash
  (JNIEnv *, jobject, jdoubleArray, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    getDashCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoContext_getDashCount
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setFillRule
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setFillRule
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    getFillRule
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoContext_getFillRule
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setLineCap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setLineCap
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    getLineCap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoContext_getLineCap
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setLineJoin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setLineJoin
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    getLineJoin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoContext_getLineJoin
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setLineWidth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setLineWidth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    getLineWidth
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_jcairo_CairoContext_getLineWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setMiterLimit
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setMiterLimit
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    getMiterLimit
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_jcairo_CairoContext_getMiterLimit
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setOperator
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setOperator
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    getOperator
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoContext_getOperator
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setTolerance
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setTolerance
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    getTolerance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_jcairo_CairoContext_getTolerance
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    clip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_clip
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    clipPreserve
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_clipPreserve
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    resetClip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_resetClip
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    fill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_fill
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    fillPreserve
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_fillPreserve
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    inFill
 * Signature: (DD)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jcairo_CairoContext_inFill
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    mask
 * Signature: (Lorg/jcairo/CairoPattern;)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_mask
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    paint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_paint
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    paintWithAlpha
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_paintWithAlpha
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    stroke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_stroke
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    strokePreserve
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_strokePreserve
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    inStroke
 * Signature: (DD)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jcairo_CairoContext_inStroke
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    copyPage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_copyPage
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    showPage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_showPage
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    getReferenceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoContext_getReferenceCount
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    translate
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_translate
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    scale
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_scale
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    rotate
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_rotate
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    setFontSize
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_setFontSize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    showText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_showText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    selectFontFace
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_selectFontFace
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    textExtents
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_textExtents
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    newPath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_newPath
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    newSubPath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_newSubPath
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    closePath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_closePath
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    arc
 * Signature: (DDDDD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_arc
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    arcNegative
 * Signature: (DDDDD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_arcNegative
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    curveTo
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_curveTo
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    lineTo
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_lineTo
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    moveTo
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_moveTo
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    rectangle
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_rectangle
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    textPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_textPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    relCurveTo
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_relCurveTo
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    relLineTo
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_relLineTo
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoContext
 * Method:    relMoveTo
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoContext_relMoveTo
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
