/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcairo_TextExtents */

#ifndef _Included_org_jcairo_TextExtents
#define _Included_org_jcairo_TextExtents
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jcairo_TextExtents
 * Method:    x_bearing
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_jcairo_TextExtents_x_1bearing
  (JNIEnv *, jclass);

/*
 * Class:     org_jcairo_TextExtents
 * Method:    y_bearing
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_jcairo_TextExtents_y_1bearing
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_TextExtents
 * Method:    width
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_jcairo_TextExtents_width
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_TextExtents
 * Method:    height
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_jcairo_TextExtents_height
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_TextExtents
 * Method:    x_advance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_jcairo_TextExtents_x_1advance
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_TextExtents
 * Method:    y_advance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_jcairo_TextExtents_y_1advance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
