/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcairo_SvgSurface */

#ifndef _Included_org_jcairo_SvgSurface
#define _Included_org_jcairo_SvgSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jcairo_SvgSurface
 * Method:    createSurfaceSvg
 * Signature: (Ljava/lang/String;DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_SvgSurface_createSurfaceSvg
  (JNIEnv *, jobject, jstring, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
