/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcairo_CairoSurface_SurfaceType */

#ifndef _Included_org_jcairo_CairoSurface_SurfaceType
#define _Included_org_jcairo_CairoSurface_SurfaceType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
