/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcairo_ImageSurface */

#ifndef _Included_org_jcairo_ImageSurface
#define _Included_org_jcairo_ImageSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jcairo_ImageSurface
 * Method:    createSurfaceImage
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_ImageSurface_createSurfaceImage
  (JNIEnv *, jobject, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
