/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcairo_CairoSurface */

#ifndef _Included_org_jcairo_CairoSurface
#define _Included_org_jcairo_CairoSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jcairo_CairoSurface
 * Method:    status
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoSurface_status
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoSurface_release
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoSurface_finish
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoSurface_flush
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    getContent
 * Signature: ()Lorg/jcairo/CairoSurface/Content;
 */
JNIEXPORT jobject JNICALL Java_org_jcairo_CairoSurface_getContent
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    getReferenceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoSurface_getReferenceCount
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    hasShowTextGlyphs
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jcairo_CairoSurface_hasShowTextGlyphs
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    markDirty
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoSurface_markDirty
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    markDirtyRectangle
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoSurface_markDirtyRectangle
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    setDeviceOffsett
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoSurface_setDeviceOffsett
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    setFallbackResolution
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoSurface_setFallbackResolution
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    copyPage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoSurface_copyPage
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    showPage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoSurface_showPage
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    getType
 * Signature: ()Lorg/jcairo/CairoSurface/SurfaceType;
 */
JNIEXPORT jobject JNICALL Java_org_jcairo_CairoSurface_getType
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoSurface
 * Method:    writeToPNG
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoSurface_writeToPNG
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
