/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcairo_PdfSurface */

#ifndef _Included_org_jcairo_PdfSurface
#define _Included_org_jcairo_PdfSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jcairo_PdfSurface
 * Method:    createSurfacePdf
 * Signature: (Ljava/lang/String;DD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_PdfSurface_createSurfacePdf
  (JNIEnv *, jobject, jstring, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
