/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcairo_CairoPattern */

#ifndef _Included_org_jcairo_CairoPattern
#define _Included_org_jcairo_CairoPattern
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jcairo_CairoPattern_EXTEND_NONE
#define org_jcairo_CairoPattern_EXTEND_NONE 0L
#undef org_jcairo_CairoPattern_EXTEND_REPEAT
#define org_jcairo_CairoPattern_EXTEND_REPEAT 1L
#undef org_jcairo_CairoPattern_EXTEND_REFLECT
#define org_jcairo_CairoPattern_EXTEND_REFLECT 2L
#undef org_jcairo_CairoPattern_EXTEND_PAD
#define org_jcairo_CairoPattern_EXTEND_PAD 3L
#undef org_jcairo_CairoPattern_PATTERN_TYPE_SOLID
#define org_jcairo_CairoPattern_PATTERN_TYPE_SOLID 0L
#undef org_jcairo_CairoPattern_PATTERN_TYPE_SURFACE
#define org_jcairo_CairoPattern_PATTERN_TYPE_SURFACE 1L
#undef org_jcairo_CairoPattern_PATTERN_TYPE_LINEAR
#define org_jcairo_CairoPattern_PATTERN_TYPE_LINEAR 2L
#undef org_jcairo_CairoPattern_PATTERN_TYPE_RADIAL
#define org_jcairo_CairoPattern_PATTERN_TYPE_RADIAL 3L
#undef org_jcairo_CairoPattern_FILTER_FAST
#define org_jcairo_CairoPattern_FILTER_FAST 0L
#undef org_jcairo_CairoPattern_FILTER_GOOD
#define org_jcairo_CairoPattern_FILTER_GOOD 1L
#undef org_jcairo_CairoPattern_FILTER_BEST
#define org_jcairo_CairoPattern_FILTER_BEST 2L
#undef org_jcairo_CairoPattern_FILTER_NEAREST
#define org_jcairo_CairoPattern_FILTER_NEAREST 3L
#undef org_jcairo_CairoPattern_FILTER_BILINEAR
#define org_jcairo_CairoPattern_FILTER_BILINEAR 4L
#undef org_jcairo_CairoPattern_FILTER_GAUSSIAN
#define org_jcairo_CairoPattern_FILTER_GAUSSIAN 5L
/*
 * Class:     org_jcairo_CairoPattern
 * Method:    addColorStop
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoPattern_addColorStop
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    addColorStopWithAlpha
 * Signature: (DDDDD)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoPattern_addColorStopWithAlpha
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    getColorStopCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoPattern_getColorStopCount
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    create
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoPattern_create
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    createWithAlpha
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoPattern_createWithAlpha
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    createLinear
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoPattern_createLinear
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    createRadial
 * Signature: (DDDDDD)I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoPattern_createRadial
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    reference
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoPattern_reference
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoPattern_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    status
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoPattern_status
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    setExtend
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoPattern_setExtend
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    getExtend
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoPattern_getExtend
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    setFilter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jcairo_CairoPattern_setFilter
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    getFilter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoPattern_getFilter
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoPattern_getType
  (JNIEnv *, jobject);

/*
 * Class:     org_jcairo_CairoPattern
 * Method:    getReferenceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jcairo_CairoPattern_getReferenceCount
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
