/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jcairo_CairoContext_LineCap */

#ifndef _Included_org_jcairo_CairoContext_LineCap
#define _Included_org_jcairo_CairoContext_LineCap
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jcairo_CairoContext_LineCap_BUTT
#define org_jcairo_CairoContext_LineCap_BUTT 0L
#undef org_jcairo_CairoContext_LineCap_ROUND
#define org_jcairo_CairoContext_LineCap_ROUND 1L
#undef org_jcairo_CairoContext_LineCap_SQUARE
#define org_jcairo_CairoContext_LineCap_SQUARE 2L
#ifdef __cplusplus
}
#endif
#endif
